dist: bionic
language: python
python: 
    - 3.8

addons:
    apt:
        packages:
            - wget

install:
    - pip install -r requirements.txt
    - pip install coverage==4.5.4
    - pip install python-coveralls
    
before_script:
    - wget https://github.com/vchain-us/immudb/releases/download/v0.9.1/immudb-v0.9.1-linux-amd64-static -O immudb
    - chmod +x immudb
    - ./immudb -d --signingKey tests/certs/my.key.pem

scripts: pytest

after_success:
    - coverage run -m pytest tests
    - coveralls
    
