dist: bionic
language: python
python: 
    - 3.8

addons:
    apt:
        packages:
            - wget
            - unzip

stage:
    - getgo
    - immudbbuild
    - pythontest
    
install:
    - pip install -r requirements.txt

    
before_script:
    - wget https://golang.org/dl/go1.15.1.linux-amd64.tar.gz
    - sudo tar -C /usr/local -xzf go1.15.1.linux-amd64.tar.gz
    - wget https://github.com/codenotary/immudb/archive/master.zip
    - unzip master.zip
    - PATH="/usr/local/go/bin/:$PATH" make -C immudb-master
    - immudb-master/immudb -d

scripts: pytest

    
