dist: bionic
language: python
python: 
    - 3.8

addons:
    apt:
        packages:
            - wget

install:
    - pip install -r requirements.txt
    - pip install coverage==4.5.4
    - pip install python-coveralls
    
before_script:
    - wget https://github.com/vchain-us/immudb/releases/download/v0.8.0/immudb-v0.8.0-linux-amd64-static 
    - chmod +x immudb-v0.8.0-linux-amd64-static
    - ./immudb-v0.8.0-linux-amd64-static -d

scripts: pytest

after_success:
    - coverage run -m pytest tests
    - coveralls
    
