dist: bionic
language: python
python: 
    - 3.8

addons:
    apt:
        packages:
            - wget
            - unzip

stage:
    - getgo
    - immudbbuild
    - pythontest
    
install:
    - pip install -r requirements.txt

jobs:
    include:
        - stage: getgo
          name: "GetGo"
          script:
            - wget https://golang.org/dl/go1.15.1.linux-amd64.tar.gz
            - tar -xzf go1.15.1.linux-amd64.tar.gz
            - echo "Current directory: $(pwd)"
        - stage: immudbbuild
          name: "ImmuDBBuild"
          script:
            - wget https://github.com/codenotary/immudb/archive/master.zip
            - unzip master.zip
            - PATH="$(pwd)/go/bin/:$PATH" make -C immudb-master
            - immudb-master/immudb -d
          
        - stage: pythontest
          name: "PythonTest"
          script: pytest

    
