name: CI
on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      immudb:
        image: codenotary/immudb:latest
        ports:
        - 3322:3322
        options: --health-cmd "immuadmin status" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          make init
          make dev
      - name: Run tests
        run: |
          make test
      - name: Run linter (pep8)
        run : |
          pip install autopep8
          export PATH="$HOME/.local/bin":$PATH
          autopep8 --exit-code --diff immudb/*.py immudb/handler/*.py
